_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.20
            "5": 0.19.0
            "6": 4.47.0
            "8":
                - 5
                - 9
            "12": 0.19.0
            "13": linux-x86_64
batch_size:
    value: 32
dataset_name:
    value: ml-1m
embedding_module_type:
    value: withtext
learning_rate:
    value: 0.001
max_sequence_length:
    value: 200
num_epochs:
    value: 101
